### ISSUE TITLE
Error when remotely invoking CLI commands

### ISSUE THREAD

**Issue by gordonje** [rji-futures-lab/tweets-to-text#9]
Zappa supports [remote function invocation](https://github.com/Miserlou/Zappa#remote-function-invocation), but I've yet to get this working for the custom CLI commands I've created.

For example, if I try `zappa invoke prod 'tweets2text.commands.twitter.get_webhook_info_command'`, I get the following error:

```
'LambdaContext' object has no attribute 'replace': AttributeError
Traceback (most recent call last):
  File "/var/task/handler.py", line 567, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
  return handler.handler(event, context)
  File "/var/task/handler.py", line 372, in handler
  result = self.run_function(app_function, event, context)
  File "/var/task/handler.py", line 277, in run_function
  result = app_function(event, context) if varargs else app_function(event)
  File "/var/task/click/core.py", line 722, in __call__
  return self.main(*args, **kwargs)
  File "/var/task/click/core.py", line 692, in main
  _bashcomplete(self, prog_name, complete_var)
  File "/var/task/click/core.py", line 31, in _bashcomplete
  complete_var = '_%s_COMPLETE' % (prog_name.replace('-', '_')).upper()
AttributeError: 'LambdaContext' object has no attribute 'replace'
```

**Comment by gordonje** [comment]
Possibly these commands need to be [“custom scripts”](http://flask.pocoo.org/docs/1.0/cli/?highlight=commands#custom-scripts)?

**Comment by gordonje** [comment]
Should be resolved by shift from flask to django and/or extending the lifespan of the lambda function.
